{
 "title": "Clash dashboard",
 "description": "Clash exporter example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "request_id" },
   { "name": "host" },
   {
    "name": "source",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, source)"
    }
   },
   {
    "name": "policy",
    "label": "policy",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, policy)"
    }
   },
   {
    "name": "type",
    "label": "type",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, type)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "版本",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max (clash_info) by (version, premium)"
    }
   ]
  },
  {
   "title": "总下载量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_download_bytes_total" }
   ]
  },
  {
   "title": "总上传量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_upload_bytes_total" }
   ]
  },
  {
   "title": "DNS 请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clash_tracing_dns_request_duration_milliseconds_count)"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_active_connections" }
   ]
  },
  {
   "title": "实时网速",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"download\"}[30s]))",
     "legendFormat": "download"
    },
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"upload\"}[1m]))",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "客户端总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (source) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "代理总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (policy) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"})",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "目的地总流量",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (destination) (clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"})))",
     "legendFormat": "来源"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 } },
  { "title": "流量统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "策略流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (policy) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (policy) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户端流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source) (increase(source_policy_type:clash_network_traffic_bytes_total:sum{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "时延统计",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "规则匹配耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(clash_tracing_rule_match_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_rule_match_duration_milliseconds_count{}[1m]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_rule_match_duration_milliseconds_bucket{}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "代理切换耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(clash_tracing_proxy_dial_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_proxy_dial_duration_milliseconds_count{}[1m]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_proxy_dial_duration_milliseconds_bucket{}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DNS 查询时延",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(clash_tracing_dns_request_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_dns_request_duration_milliseconds_count{}[1m]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_dns_request_duration_milliseconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 } },
  { "title": "详细日志", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  { "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 } },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 } },
  { "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 } }
 ]
}