version: "3.0"
services:
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: unless-stopped
    user: "0:0"  # root
    volumes:
      - ./grafana/data:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "0:0"  # root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    user: "0:0"  # root
    ports:
      - 3100:3100
    volumes:
      - ./loki/data:/loki
      - ./loki/config.yaml:/etc/loki/local-config.yaml


  clash-exporter:
    image: zzde/clash-exporter:latest
    container_name: clash-exporter
    entrypoint:
      ["/app/clash-exporter", "-collectTracing=true", "-collectDest=true"]
    environment:
      - CLASH_HOST=Your_clash_board_ip:port
      - CLASH_TOKEN=Your_clash_board_secret
    restart: always
    ports:
      - 2112:2112
  
  vector:
    image: timberio/vector:0.X-alpine
    container_name: vector
    restart: unless-stopped
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      # - ./vector/vector.toml:/etc/vector/vector.toml
    depends_on:
      - loki

  scraper:
    image: vi0oss/websocat:0.10.0
    container_name: scraper
    restart: unless-stopped
    environment:
      - CLASH_HOST=ip:port
      - CLASH_TOKEN=secret
      - VECTOR_IP=ip:port
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/local/bin/websocat -v --autoreconnect-delay-millis 15000 autoreconnect:ws://${CLASH_HOST}/traffic?token=${CLASH_TOKEN} autoreconnect:tcp:${VECTOR_IP} &
        /usr/local/bin/websocat -v --autoreconnect-delay-millis 15000 autoreconnect:ws://${CLASH_HOST}/profile/tracing?token=${CLASH_TOKEN} autoreconnect:tcp:${VECTOR_IP}
    depends_on:
      - vector
